name: Compile and check norm

on:
  push:
    branches: [ "master"]
  pull_request:
    branches: [ "master"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile files with Makefile
        run: make

      - name: norminette
        uses: alexandregv/norminette-action@v3
        with:
          flags: '.'

