name: Check Norminette

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  norminette:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Norminette
        run: |
            sudo gem install norminette

      - name: Run Norminette
        id: norminette
        run: norminette || echo "::set-output name=norminette-passed::false"

      - name: Check Norminette results
        run: |
          if [ "${{ steps.norminette.outputs.norminette-passed }}" == "false" ]; then
            echo "Norminette check failed. Please fix the coding standard issues."
            exit 1
          else
            echo "Norminette check passed successfully."
          fi